version: '3'

services:
# this is a gunicorn server, you can name what ever you want, I call it 'django_gunicorn'
  web:
    build: .
    command: python core/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
    - "8000:8000"