# Generated by Django 4.1.1 on 2022-09-08 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="usermodel",
            options={"verbose_name": "Users", "verbose_name_plural": "Users"},
        ),
    ]
